apiVersion: v1
data:
  container-helper.yaml: |
    ---
    response: "Selma"
    tcpchecks:
      - name: marge.simpson
        host: marge-service.simpson
        port: 8080
      - name: homer.simpson
        host: homer-service.simpson
        port: 8080
      - name: patty.bouvier
        host: patty-service.bouvier
        port: 8080
kind: ConfigMap
metadata:
  labels:
    app: selma
  name: selma-container-helper-yaml-5kctckk27b
  namespace: bouvier
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: selma
  name: selma-service
  namespace: bouvier
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: selma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: selma
  name: selma-deployment
  namespace: bouvier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selma
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      labels:
        app: selma
    spec:
      containers:
      - name: container-helper
        image: quay.io/openshift-examples/container-helper:ubi8-minimal
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /container-helper/
          name: container-helper-yaml
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 25m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: container-helper-yaml
        configMap:
          name: selma-container-helper-yaml-5kctckk27b
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: selma
  name: selma-route
  namespace: bouvier
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: selma-service
    weight: 100
  wildcardPolicy: None
